### ISSUE TITLE
specifying hub_model in create_project not working

### ISSUE THREAD

**Issue by stubbi** [huggingface/autonlp#102]
I tried to create a project with the given configuration:

```
project = client.create_project(name="project", task="single_column_regression", language="en", max_models=1, hub_model="EleutherAI/gpt-neo-2.7B")
```

and keep getting

```
---------------------------------------------------------------------------
HTTPError                                 Traceback (most recent call last)
<ipython-input-23-f15ed7bdca2f> in <module>
----> 1 project = client.create_project(name="project", task="single_column_regression", language="en", max_models=1, hub_model="EleutherAI/gpt-neo-2.7B")
      2

/usr/local/lib/python3.7/site-packages/autonlp/autonlp.py in create_project(self, name, task, language, max_models, hub_model)
     95             },
     96         }
---> 97         json_resp = http_post(path="/projects/create", payload=payload, token=self.token).json()
     98         proj_name = json_resp["proj_name"]
     99         created = json_resp["created"]

/usr/local/lib/python3.7/site-packages/autonlp/utils.py in http_post(path, token, payload, domain, suppress_logs, **kwargs)
     64     except requests.exceptions.ConnectionError:
     65         raise UnreachableAPIError("❌ Failed to reach AutoNLP API, check your internet connection")
---> 66     response.raise_for_status()
     67     return response
     68 

/usr/local/lib/python3.7/site-packages/requests/models.py in raise_for_status(self)
    941 
    942         if http_error_msg:
--> 943             raise HTTPError(http_error_msg, response=self)
    944 
    945     def close(self):

HTTPError: 400 Client Error: Bad Request for url: https://api.autonlp.huggingface.co/projects/create
```

also if I specify other models like `gpt2`. It works when I set `hub_model=""`, though. Is the problem the models I try to specify which do not support the `single_column_regression` task?

**Comment by SBrandeis** [comment]
Hi @stubbi!

You have to set the language as `unk` to be able to use a model form the hub.
The following snippet should solve your issue:
```python
project = client.create_project(
    name="project",
    task="single_column_regression",
    language="unk",  # <-- Notice the change from "en" to "unk"
    max_models=1,
    hub_model="EleutherAI/gpt-neo-2.7B"
)
```

I'll let @abhishekkrthakur intervene if I'm mistaken, but I don't think you'll be able to train `EleutherAI/gpt-neo-2.7B` on a single column regression task. Only models compatible with the Fill Mask pipeline can be trained for this task.
You can find a list of such models here: https://huggingface.co/models?pipeline_tag=fill-mask

Let me know if it helps !

**Comment by stubbi** [comment]
@SBrandeis thanks for that hint! It works with `language=unk`. Regarding the `Fill Mask pipeline`, I just started it on a small dataset to see if it would work. No problems so far, task was successfully queued.

**Comment by stubbi** [comment]
Also, if you like, I'd be happy to make changes to add the necessary checks and give appropriate error messages to the user.

**Comment by SBrandeis** [comment]
>  I'd be happy to make changes to add the necessary checks and give appropriate error messages to the user.

That would be much appreciated @stubbi 🤗 Feel free to open a PR with the changes, we'll be happy to review it!

**Comment by stubbi** [comment]
Will have the time for it over the weekend or beginning of next week 👍 

Also, now I set `hub_model="google/bigbird-roberta-large"` which is supposed to be compatible with the `Fill Mask pipeline`. Training ended with `success`, but the model always only seems to predict `target: 1` and the losses also look like nothing really happened during the training. Have I done anything else wrong?

```
Model ID | Loss | MSE | rMSE | MAE | R2 | Explained Variance
#6401380 cavernous-grouse | 9109603.0000 | 9109602.0000 | 3018.2117 | 2213.0327 | -0.0000 | 0.0000
```  

It looked similar before when I set the model to `EleutherAI/gpt-neo-2.7B`.

**Comment by abhishekkrthakur** [comment]
Thank you for reporting this issue. I'll take a look at these two models today.

**Comment by stubbi** [comment]
Thanks, @abhishekkrthakur! 🙂

**Comment by stubbi** [comment]
@abhishekkrthakur could you already figure out something?

**Comment by abhishekkrthakur** [comment]
there was an issue but now you can train bigbird. however, its not recommended as bigbird was written with tpu in mind and autonlp doesn't support tpu yet. so, it will take unnecessarily huge amount of time.
