### ISSUE TITLE
cvs/json error even for valid csv

### ISSUE THREAD

**Issue by Samirun** [huggingface/autonlp#121]
@lewtun  I have been facing issues while training  with csv files

auto nlp is not allowing to train even simple csv  data saying  it has an error.
can you test from your side
![image](https://user-images.githubusercontent.com/46156330/148943460-764e4567-9add-433f-af5c-448aa746260d.png)
![image](https://user-images.githubusercontent.com/46156330/148943595-8dfeb4ee-b11f-49da-a032-cd02bb3c175a.png)

not even simple data like above is being recognised as vali data. can any one check this issue?
@coyotte508

**Comment by abhishekkrthakur** [comment]
would it be possible for you to share the first few lines of the CSV you are trying to upload?

**Comment by abhishekkrthakur** [comment]
i just tested the ui with a sample CSV file for multi label classification. so, if you can provide your data, i can look further. if that's not an option, please try reading it with `pandas` and see if pandas is able to read, then save the data again with `.to_csv` with `index=False`.

**Comment by Samirun** [comment]
@abhishekkrthakur  i can't share the data publicly.  i tried reading through pandas its working fine.
can we breifly connect ?can send you an invite in teams?

**Comment by Samirun** [comment]
here is the sample data
a,b
--
2 | I fix it told you that,intent_outage_fixed
3 | Reply fixed,intent_outage_fixed
4 | FIXED,intent_outage_fixed
5 | Fixed,intent_outage_fixed
6 | This problem was resolved yesterday,intent_outage_fixed
7 | FIXED thank you,intent_outage_fixed
8 | FIXED -Thank you!,intent_outage_fixed
9 | fixed Thankyou   yeah!,intent_outage_fixed
10 | resolved Thank you very much,intent_outage_fixed
11 | Work has been completed.,intent_outage_fixed
12 | Thanks for fixing it quickly,intent_outage_fixed
13 | FIXED! Yay!,intent_outage_fixed
14 | It's fixed.,intent_outage_fixed

**Comment by abhishekkrthakur** [comment]
@Samirun let's discuss via email: autonlp [at] huggingface [dot] co

**Comment by Samirun** [comment]
@abhishekkrthakur i have just sent an email could you please check

**Comment by Samirun** [comment]
not enough data under lables.issue has been resolved.thanks @abhishekkrthakur
