### ISSUE TITLE
Correct Way To Run (Pegasus) Summarization Models Locally?

### ISSUE THREAD

**Issue by mitchellgordon95** [huggingface/autonlp#122]
We've trained a summarization model via AutoNLP that we've been successfully using with the Accelerated Inference API for a few weeks. We'd like to start running this model on our own GPUs to decrease cost. 

The model we selected was `PegasusForConditionalGeneration`. We've successfully run the model locally using something like

```python
device = 0 if torch.cuda.is_available() else -1
tokenizer = AutoTokenizer.from_pretrained("/mnt/models")
model = AutoModelForSeq2SeqLM.from_pretrained("/mnt/models")
pipeline = pipeline('summarization', model, tokenizer=tokenizer, device=device)
output = pipeline(input_text)
```
or also
```python
tokenizer = AutoTokenizer.from_pretrained("/mnt/models")
model = AutoModelForSeq2SeqLM.from_pretrained("/mnt/models").cuda()
input_ids = self.tokenizer(input_text, return_tensors="pt")['input_ids']
output_ids = self.model.generate(input_ids=input_ids.cuda())
output = tokenizer.batch_decode(output_ids, skip_special_tokens=True, clean_up_tokenization_spaces=False)[0]
```
where `/mnt/models` points to the downloaded model repository from the Huggingface model hub.

However, neither of these methods give the same results as the Accelerated Inference API, given the same input. We suspect that perhaps tokenization is being performed differently, or the model is being called with different parameters.

Is there somewhere we can confirm exactly how the Accelerated API is loading and calling the model?

**Comment by SBrandeis** [comment]
Hi @mitchellgordon95 !

The preferred point of contact for inference API related questions is the following email address:
`api-enterprise[at]huggingface[dot]co`

I'm closing this issue since it's not directly related to AutoNLP
