### ISSUE TITLE
Training failed how to restart training?

### ISSUE THREAD

**Issue by gorkemgoknar** [huggingface/autonlp#33]
So training failed, how to re-train it due to a server error or something?
autonlp is latest version, python is 3.9

gorkemgoknar@Gorkem-MacBook-Pro:~/Desktop/autonlptest$ autonlp project_info --name sentiment_turkish
2021-03-11 16:35:20.687 | INFO     | autonlp.cli.project_info:run:28 - Fetching info for project: sentiment_turkish
2021-03-11 16:35:20.688 | INFO     | autonlp.autonlp:_login_from_conf:66 - 🗝 Retrieving credentials from config...
2021-03-11 16:35:20.688 | INFO     | autonlp.autonlp:get_project:109 - ☁ Retrieving project 'sentiment_turkish' from AutoNLP...
2021-03-11 16:35:21.205 | INFO     | autonlp.project:refresh:195 - 🔄 Refreshing uploaded files information...
2021-03-11 16:35:21.700 | INFO     | autonlp.project:refresh:200 - 🔄 Refreshing models information...
2021-03-11 16:35:22.206 | INFO     | autonlp.autonlp:get_project:121 - ✅ Successfully loaded project: 'sentiment_turkish'!
AutoNLP Project (id # 29)
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 • Name:        sentiment_turkish
 • Owner:       gorkemgoknar
 • Status:      ❌ Failed to download data files from the huggingface hub
 • Task:        Binary Classification
 • Created at:  2021-03-11 12:51 Z
 • Last update: 2021-03-11 13:34 Z

~~~~~~~~~~~~~~ Files ~~~~~~~~~~~~~~

Dataset ID:
gorkemgoknar/autonlp-data-sentiment_turkish

📁 turkish_movie_train.csv (id # 27)
   • Split:             train
   • Processing status: ❌ Failed: server error
   • Last update:       2021-03-11 13:20 Z
📁 turkish_movie_valid.csv (id # 28)
   • Split:             valid
   • Processing status: ❓ Unhandled status! Please update autonlp
   • Last update:       2021-03-11 13:32 Z

~~~~~~~~~~~~ Models ~~~~~~~~~~~

🤷 No train jobs started yet!

**Comment by SBrandeis** [comment]
Hello @gorkemgoknar !

It looks like you're not running the latest version of AutoNLP. You can run: `pip install --upgrade autonlp` to update!

You selected a `binary_classification` task for your project, but the validation file you've uploaded contains more 2 categories: as updating the task of a project is not supported in AutoNLP yet, you will need to create another project and select **`multi_class_classification`** as task to proceed.

Plus, we are having trouble decoding your files. Could you run this before uploading the files, please?
```python
import pandas as pd
pd.read_csv("turkish_movie_train.csv").to_csv("turkish_movie_train.csv")
pd.read_csv("turkish_movie_valid.csv").to_csv("turkish_movie_valid.csv")
```

**Comment by gorkemgoknar** [comment]
Thanks @SBrandeis.
I will retry after cleaning up csv file.

My installed autonlp is 0.1.9 (which I can found out by upgrading it), maybe you should add version info to package __version__ also while upgrading.
>>> autonlp.__version__
'0.0.1'

For information file format is like this (language is Turkish plain-text, characters are iso-8859-9 encoded usually)
comment,film_name,point
"     Jean Reno denince zaten leon filmi gelir akla izlemeyen kalmamıştır ama kaldıysada ee ne duruyorsun hemen izle :)
  ",Sevginin Gücü,"5,0"\n


Classes are 1 to 5 so it is better to make it as a regression problem maybe, or do a preprocessing to make it <2.5 0 and upper 1.

I wanted to directly test it out with a common dataset but it seems we need to do additional preprocessing for training and validation dat and take care of non-ascii character texts. 

Prediction is as good as its data anyway..

**Comment by halilyesilceng** [comment]
![image](https://user-images.githubusercontent.com/48108295/113072236-42ce3480-91cf-11eb-8258-43fef4586faa.png)
I have a same issue. Could you help me for this ?

**Comment by SBrandeis** [comment]
Hi @halilyesilceng!
Please make sure your files can be loaded with the [`datasets`](https://github.com/huggingface/datasets) library:
```python
from datasets import load_dataset
dset = load_dataset("json", data_files=["/path/to/your/file.json"], split="train")
```
Let me know if this helps!
