### ISSUE TITLE
Docs - Entity Extraction page is empty

### ISSUE THREAD

**Issue by zephyrous** [huggingface/autonlp#36]
Hi all, thanks for this amazing product!

I am currently testing various features on the trial version, but the Entity Extraction documentation page at https://huggingface.co/docs/autonlp/entity_extraction.html is currently empty. Is this feature not offered yet? Or can I find its documentation elsewhere? Thanks!

**Comment by SBrandeis** [comment]
Hi @zephyrous !

This part of the documentation has not been deployed yet, we apologize for the inconvenience.

Still, entity extraction is fully supported in AutoNLP!
It expects JSON lines files (**1 valid JSON document per line**), where each line / JSON document contains two fields:
- One containing the tokens to identify, as a list of strings
- One containing the tags of the tokens, as a list of strings

Example:
```JSON
// train.jsonl
{"tokens": ["I", "love", "AutoNLP", "!"], "tags": ["PRON", "VERB", "OBJ", "PUNCT"]}
{"tokens": ["Hello", "there", "!"], "tags": ["EXPR", "LOC", "PUNCT"]}
```

Let us know if you have any further question!

**Comment by zephyrous** [comment]
Lovely, thanks!

**Comment by SBrandeis** [comment]
I'm closing this issue, but feel free to re-open if you have any further questions!

**Comment by zephyrous** [comment]
Hi again,

I have now created two json files (one for training and one for validation). They are in the form:
{"tokens": ["I", "love", "AutoNLP", "!"], "tags": ["PRON", "VERB", "OBJ", "PUNCT"]}
{"tokens": ["Hello", "there", "!"], "tags": ["EXPR", "LOC", "PUNCT"]}

Can you please give an example of the commands needed for training and validation data respectively, @SBrandeis? Many thanks in advance.

**Comment by SBrandeis** [comment]
Hi @zephyrous,

**Comment by SBrandeis** [comment]
Hello @zephyrous, I had a look at your project, it seems like some of the files you uploaded with the CLI tool had a wrong column mapping. We do not support updating the column mapping of an uploaded file yet, so I would advise to create a fresh project and start over.

For more details about what is expected as a column mapping in AutoNLP, you can run:
```bash
autonlp upload --help
```
Also, we have added column mapping validation in recent versions of AutoNLP. Please make sure you have the latest version of AutoNLP installed in your environment:
```bsh
pip install --upgrade autonlp
```

Let me know if this helps 😄

**Comment by zephyrous** [comment]
Thank you so much, training has successfully started :)
