### ISSUE TITLE
a question for using autonlp for very little data

### ISSUE THREAD

**Issue by deven367** [huggingface/autonlp#45]
Hello, I was planning to use autonlp for a personal project of mine for multi class classification. I have generated sentence embeddings for a lot of sentences and they have labels, which I am planning to use as data. I have very little data for training the model, around 200 data points. Shall I try using autonlp or shall I use something else? Thanks.

**Comment by SBrandeis** [comment]
Hi @deven367 !
You should definitely try out AutoNLP for your use case.
Bear in mind that AutoNLP only accepts text as input for now.
AutoNLP will generate a cost estimate for you before the training actually gets started, and you will have the opportunity to cancel or proceed with the training at that time.

**Comment by deven367** [comment]
That helps! Thank you.
