### ISSUE TITLE
Brazilian Portuguese (pt-BR) language support

### ISSUE THREAD

**Issue by HinePo** [huggingface/autonlp#57]
Really anxious for this feature!

**Comment by SBrandeis** [comment]
Hi @HinePo,
Support for Portuguese is on the way and should be announced and released very soon!

**Comment by abhi1thakur** [comment]
Sorry for the delay, Portuguese is now supported.

**Comment by HinePo** [comment]
That's awesome! Many thanks for everyone on the team!
