### ISSUE TITLE
Domain specific pre-training and Question Answering 

### ISSUE THREAD

**Issue by almugabo** [huggingface/autonlp#59]
Hallo, 
this is more an inquiry about future features than "an issue" on currently implemented functionalities. 

(1) are you planning to add the QA task too ? 
(2) Are you planning to offer also the possibility to continue pre-training on a specific domain ?  ( I include  a chart to show what I mean) 

![image](https://user-images.githubusercontent.com/6864475/115027341-e011b400-9ec3-11eb-953e-8db35e11ddd0.png)

**Comment by abhi1thakur** [comment]
QA task is planned for near future!

**Comment by almugabo** [comment]
thanks
