### ISSUE TITLE
AutoNLP error with Git clone during data upload (python)

### ISSUE THREAD

**Issue by lrsoenksen** [huggingface/autonlp#60]
When calling the "project.upload" function in python I get the following error:
I've substituted the AutoNLP api token with "API_TOKEN" and the folder/model name with MODEL_PATH. How can I fix it?

---------------------------------------------------------------------------
CalledProcessError                        Traceback (most recent call last)
~/opt/anaconda3/envs/aitoci_py37/lib/python3.7/site-packages/huggingface_hub/repository.py in clone_from(self, repo_url, use_auth_token)
    147                     encoding="utf-8",
--> 148                     cwd=self.local_dir,
    149                 )

~/opt/anaconda3/envs/aitoci_py37/lib/python3.7/subprocess.py in run(input, capture_output, timeout, check, *popenargs, **kwargs)
    511             raise CalledProcessError(retcode, process.args,
--> 512                                      output=stdout, stderr=stderr)
    513     return CompletedProcess(process.args, retcode, stdout, stderr)

CalledProcessError: Command '['git', 'clone', 'https://user:API_TOKEN@huggingface.co/datasets/MODEL_PATH', '.']' returned non-zero exit status 128.

During handling of the above exception, another exception occurred:

OSError                                   Traceback (most recent call last)
<ipython-input-3-c24c1d3c317b> in <module>
      5     col_mapping={
      6         "document":"text",
----> 7         "summary":"target"})
      8 
      9 # Upload the validation set

~/opt/anaconda3/envs/aitoci_py37/lib/python3.7/site-packages/autonlp/project.py in upload(self, filepaths, split, col_mapping, path_to_audio)
    224             raise ValueError("'path_to_audio' must be provided when task is 'speech_recognition'")
    225 
--> 226         dataset_repo = self._clone_dataset_repo()
    227         local_dataset_dir = dataset_repo.local_dir
    228 

~/opt/anaconda3/envs/aitoci_py37/lib/python3.7/site-packages/autonlp/project.py in _clone_dataset_repo(self)
    364             local_dir=local_dataset_dir,
    365             clone_from=clone_from,
--> 366             use_auth_token=self._token,
    367         )
    368         try:

~/opt/anaconda3/envs/aitoci_py37/lib/python3.7/site-packages/huggingface_hub/repository.py in __init__(self, local_dir, clone_from, use_auth_token, git_user, git_email)
     59 
     60         if clone_from is not None:
---> 61             self.clone_from(repo_url=clone_from, use_auth_token=use_auth_token)
     62         else:
     63             if os.path.isdir(os.path.join(self.local_dir, ".git")):

~/opt/anaconda3/envs/aitoci_py37/lib/python3.7/site-packages/huggingface_hub/repository.py in clone_from(self, repo_url, use_auth_token)
    218 
    219         except subprocess.CalledProcessError as exc:
--> 220             raise EnvironmentError(exc.stderr)
    221 
    222     def git_config_username_and_email(

OSError: Cloning into '.'...
remote: Repository not found.
fatal: repository 'https://huggingface.co/datasets/MODEL_PATH/' not found

**Comment by SBrandeis** [comment]
Hello @lrsoenksen,
We're sorry you encountered issues with AutoNLP.
Each AutoNLP project is backed by a private `dataset` git repository in your namespace on the HuggingFace hub.
Most likely, there was some issues and / or delay while creating this `dataset` repository, which caused the exception.
To solve this, you can either create the repository manually on the HuggingFace hub, or create a new project.
Let me know if this helps!

**Comment by lrsoenksen** [comment]
It seems that this behavior was happening when I wanted to re-create a project for which I had deleted a model or a dataset in my HuggingFace account. Just creating a new project + model name seemed to do the trick. I'm running AutoNLP now with no issues.
