### ISSUE TITLE
How to eliminate AutoNLP projects

### ISSUE THREAD

**Issue by lrsoenksen** [huggingface/autonlp#61]
There is obviously the possibility of creating projects but is there a command to delete projects? Or where are those definitions stored (what is the location of the config file)

**Comment by SBrandeis** [comment]
Hi @lrsoenksen !
Deleting projects is not supported in AutoNLP yet, though we plan to add the feature soon.

**Comment by abhishekkrthakur** [comment]
you should now be able to delete the projects using autonlp UI: https://ui.autonlp.huggingface.co/
