### ISSUE TITLE
Training  in status: Failed

### ISSUE THREAD

**Issue by FernandoLpz** [huggingface/autonlp#62]
Hello,

I tried to train 5 models for my binary_classification problem however, I got this error, how can I know what went wrong to fix it and try again?

Thank you.
`📁 train.csv (id # 138)
   • Split:             train
   • Processing status: ✅ Success!
   • Last update:       2021-04-24 23:44 Z
📁 valid.csv (id # 139)
   • Split:             valid
   • Processing status: ✅ Success!
   • Last update:       2021-04-24 23:45 Z

~~~~~~~~~~~~ Models ~~~~~~~~~~~

+----+--------+--------+--------------------+--------------------+
|    |   ID   | Status |   Creation date    |    Last update     |
+----+--------+--------+--------------------+--------------------+
| ❌ | 128413 | failed | 2021-04-24 23:49 Z | 2021-04-24 23:57 Z |
| ❌ | 128414 | failed | 2021-04-24 23:49 Z | 2021-04-24 23:57 Z |
| ❌ | 128415 | failed | 2021-04-24 23:49 Z | 2021-04-24 23:57 Z |
| ❌ | 128416 | failed | 2021-04-24 23:49 Z | 2021-04-24 23:57 Z |
| ❌ | 128417 | failed | 2021-04-24 23:49 Z | 2021-04-24 23:57 Z |
+----+--------+--------+--------------------+--------------------+`

**Comment by abhi1thakur** [comment]
Thank you for reporting. We are looking into this issue and would get back to you as soon as possible.

**Comment by abhi1thakur** [comment]
@FernandoLpz , we have identified the issue and fixed it. I have forced-restarted training of all models for your project. you should now be able to see more information about training progress using `project_info` command.
Thank you for notifying.

**Comment by FernandoLpz** [comment]
@abhi1thakur , my models are now in status `success`.

Thank you so much!
