### ISSUE TITLE
How to know evaluation task is finished

### ISSUE THREAD

**Issue by albertvillanova** [huggingface/autonlp#72]
Currently, for finetuning, once the training is launched, we can know when the finetuned models are ready:
```python
project.train(noprompt=True)
project.refresh()
all_jobs_finished = all(job.status == "success" for job in project.training_jobs)
```

However, we do not have an analogue way for evaluation. Currently I keep trying to clone the evaluation model repo until this succeeds once the evaluation is finished. Indeed, I have to wait a little more after the repo is cloned, because the README file is generated in a commit some time after the repo is created.

I wonder if it would be possible to implement something similar to the finetuning case, like:
```python
evaluation_job = client.create_evaluation(...)
evaluation_job.refresh()
job_finished = (evaluation_job.status == "success")
```

**Comment by abhi1thakur** [comment]
@albertvillanova I have added it in the Python API now: `client.get_eval_job_status(eval_job_id)`
When the response is 5, it means it finished successfully. ill send you mapping in slack.
