### ISSUE TITLE
Multi Class Classification | Base Config Issue

### ISSUE THREAD

**Issue by chintanckg** [huggingface/autonlp#75]
While setting up project for Multiclass classification, in the very first step below:

(base)C:\WINDOWS\system32>autonlp create_project --name custom_classifier --language en --task multi_class_classification
> INFO    Creating project: custom_classifier with task: multi_class_classification
> INFO    🗝 Retrieving credentials from config...
> ERROR   ❌ Oops! Something failed in AutoNLP backend..
> ERROR   Error code: 400; Details: 'Invalid config: 1 validation error for BaseConfig
max_models
  field required (type=value_error.missing)'

**Comment by SBrandeis** [comment]
Hello @chintanckg, it looks like you're using an old version of AutoNLP.

Please make sure you are using the latest version of the package (`0.2.6`).

If that's not the case, you can update to the latest version by running: `pip install -U autonlp`.

Let me know if this helps!

**Comment by chintanckg** [comment]
This helped, thanks @SBrandeis.
