### ISSUE TITLE
Regression available?

### ISSUE THREAD

**Issue by stubbi** [huggingface/autonlp#79]
On the [website](https://huggingface.co/autonlp) it says that `regression` is one of the available tasks. In the documentation it's not mentioned. Is it (already) available?

**Comment by SBrandeis** [comment]
Hello @stubbi !
Yes, single column regression is available.
Documentation is not up to date, thanks for noticing!
To create a regression project in the CLI, run the following:
```bash
autonlp create_project --name <your project name> --task single_column_regression --max_models <number of desired models>
```
let me know if this helps!

**Comment by stubbi** [comment]
Thank you, @SBrandeis! 🙂 

I will try it and let you know!

**Comment by abhi1thakur** [comment]
added to docs.
