### ISSUE TITLE
Is GPT-neo also considered

### ISSUE THREAD

**Issue by stubbi** [huggingface/autonlp#90]
Will autonlp also train GPT-neo models for tasks like regression and classification?

**Comment by stubbi** [comment]
respectively, which models are considered? All of them and are the newest also included?

**Comment by abhishekkrthakur** [comment]
GPT-Neo is not in the pipeline at the moment. If you want to train it using AutoNLP, you can use single model training: https://huggingface.co/docs/autonlp/training_hub_model.html

**Comment by stubbi** [comment]
@abhishekkrthakur thanks!
